sudo: required # is required to use docker service in travis
services:
  - docker # install docker
before_install:
  - openssl aes-256-cbc -K $encrypted_ea0ac622ba29_key -iv $encrypted_ea0ac622ba29_iv -in multi-k8s-gcloud-auth.json.enc -out multi-k8s-gcloud-auth.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null; # download google cloud sdk
  - source $HOME/google-cloud-sdk/path.bash.inc # add gcloud to $PATH
  - gcloud components update kubectl # install kubectl
  - gcloud auth activate-service-account --key-file service-account.json # authenticate with google cloud
