sudo: required # is required to use docker service in travis
services:
  - docker # install docker
env:
  global:
    - SHA=$(git rev-parse HEAD) # get current commit SHA
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1 # disable prompts from google cloud sdk
before_install:
  - openssl aes-256-cbc -K $encrypted_ea0ac622ba29_key -iv $encrypted_ea0ac622ba29_iv -in multi-k8s-gcloud-auth.json.enc -out multi-k8s-gcloud-auth.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null; # download google cloud sdk
  - source $HOME/google-cloud-sdk/path.bash.inc # add gcloud to $PATH
  - gcloud components update kubectl # install kubectl
  - gcloud auth activate-service-account --key-file multi-k8s-gcloud-auth.json # authenticate with google cloud
  - gcloud config set project multi-k8s-398718 # set project
  - gcloud config set compute/zone us-west1-a # set compute zone
  - gcloud container clusters get-credentials multi-cluster # set cluster
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin # login to docker
  - docker build -t brooksbenson03/react-test -f ./client/Dockerfile.dev ./client # build test image

script:
  - docker run -e CI=true brooksbenson03/react-test npm test

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: main
